name: Lint Code

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'  

      - name: Install dependencies
        run: npm install
        working-directory: ./src/server  

      - name: Check Node.js version
        run: node -v

      - name: Check ESLint version
        run: npx eslint -v

      - name: Run ESLint
        run: npm run lint:fix
        working-directory: ./src/server  

      - name: Check for changes after lint fix
        run: git diff --exit-code
