name: Lint Code

on:
  pull_request:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21'  

      - name: Install dependencies
        run: |
          cd src/server
          npm install

      - name: Run ESLint
        id: lint
        run: |
          cd src/server
          npx eslint .  # No more "|| true" so it will fail if lint errors occur

      - name: Post PR comment if lint issues found
        if: failure()  
        uses: actions/github-script@v6
        with:
          script: |
            const pr_number = context.payload.pull_request.number;
            github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr_number,
              body: `Linting issues were detected in this pull request. Please run \`npm run lint:fix\` to resolve the issues before merging.`
            })
